### ISSUE TITLE
Need a way to determine if user is banned

### ISSUE THREAD

**Issue by ImGrumpy** [musiqpad/mqp-node-api#11]
With mqp-server 0.7.0, `banned` was removed from the user object, need a way to replace that.  I tried using `API.room.getBannedUsers` with sendJSON but had no luck. :frowning: 

A nice way to do it might be a boolean function like `isBanned(uid)`.  Or, on a larger scale, add `getBannedUsers` into the node API.

**Comment by explodingcamera** [comment]
#10 I'm currently not at home, I'll do it next week.
