### ISSUE TITLE
[Request] Add timestamps to error messages in the console

### ISSUE THREAD

**Issue by ImGrumpy** [musiqpad/mqp-node-api#7]
It's difficult to track down errors reported in the console if they happen when you're not watching, adding timestamps would help.

Current:

```
Unhandled rejection Queue is already unlocked
```

Suggested:

```
[2016-05-13 09:23:15] Unhandled rejection Queue is already unlocked
```

**Comment by explodingcamera** [comment]
Hm i'm not sure about this, normally users are supposed to do logging themselves with promise based apis. Unhandled rejection just means you forgot to .catch errors.

**Comment by ImGrumpy** [comment]
Well, using that logic, you could just forget error messages altogether and just let the program crash without explanation.

**Comment by explodingcamera** [comment]
No. The api first of all isn't a standalone programm and 2. It does throw the errors, that's bluebird. I could add the timestamps like this though: 

```
Unhandled rejection [2016-05-13 09:23:15] Queue is already unlocked
```

This way you wouldn't be able to get the full error object though and would have to use regex to remove the timestamp.

I was thinking of adding an debug option that logs everything though.

**Comment by explodingcamera** [comment]
Okay, after a bit of searching i found out about bluebird's

```
Promise.onPossiblyUnhandledRejection
```

That prevents it from just trowing to the console and I can add a real error handler to it :smiley: .

**Comment by explodingcamera** [comment]
Added in ff33466fcc41e5708aeec90cb24335fff084c1f7
