### ISSUE TITLE
New logging feature breaks existing bots if logging variable not defined

### ISSUE THREAD

**Issue by ImGrumpy** [musiqpad/mqp-node-api#8]
Not sure if this was intentional, but people upgrading to the current version (0.3.4) will find their bots break because of the new logging.

```
C:\bot\node_modules\mqp-api\src\app.js:27
      logFile: typeof args.logging.logFile !== 'undefined' ? args.logging.logFile : null,
                                  ^

TypeError: Cannot read property 'logFile' of undefined
    at new app (C:\bot\node_modules\mqp-api\src\app.js:27:35)
```

Perhaps if `logging` is not defined it could just default to 'info' level logging with no log file to allow for a safe upgrade from previous versions.

**Comment by explodingcamera** [comment]
Thank you for reporting the bug, i'll publish the new version to npm tomorrow!
